name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.GH_SECRET }}
          deploy-branch: gh-pages
          gatsby-args: --no-color
          git-config-name: lukasbachbot
          git-config-email: bot@noreply.lukasbach.com