name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v3
      - run: yarn
      - run: yarn lint:test
      - run: yarn build
        env:
          GITHUB_API_KEY: ${{ secrets.KEY_GITHUB_PAT }}
      # - run: yarn typecheck
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY_GITHUB_PAT }}
          publish_dir: ./public
          cname: lukasbach.com
          force_orphan: true
          git-user_name-name: lukasbachbot
          git-user_email-email: bot@noreply.lukasbach.com